# Generated by Django 5.1.4 on 2024-12-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionTaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('audio_file_name', models.CharField(max_length=255)),
                ('transcription', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='TranscriptionTask',
        ),
    ]
