# Generated by Django 5.1.4 on 2024-12-10 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0002_transcriptiontaskmodel_delete_transcriptiontask'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptiontaskmodel',
            name='file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
